services:
  site:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.skerter.rule=Host(`${SITE_DOMAIN}`)"
      - "traefik.http.routers.skerter.entrypoints=websecure"
      - "traefik.http.routers.skerter.tls.certresolver=le"
      - "traefik.http.services.skerter.loadbalancer.server.port=80"
      - "traefik.http.routers.skerter-http.rule=Host(`${SITE_DOMAIN}`)"
      - "traefik.http.routers.skerter-http.entrypoints=web"
      - "traefik.http.routers.skerter-http.middlewares=redirect-to-https@file"

networks:
  proxy:
    external: true
